version: '3.8'
services:

  code-test-backend:
    build: 
      context: ./
      target: code-test-backend
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    container_name: code-test-backend
    depends_on:
      - code-test-db

  code-test-db:
    image: mongo
    container_name: code-test-db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db.js:/docker-entrypoint-initdb.d/db.js:rw
      - ./mongo-volume:/data/db
      - ./.env:/.env
    ports:
      - "27017:27017"