version: '3.8'
services:

  code-test-backend:
    build: 
      context: ./
      target: code-test-backend
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    container_name: code-test-backend